[variables]
    PYTHON_VERSION = "3.10"

[phases.setup]
    nixPkgs = ["cmake", "libglvnd", "gcc", "stdenv.cc.cc.lib", "xorg.libX11", "python310"]

[phases.build]
    dependsOn = ["setup"]
    cmds = ["python -m venv /app/.venv", "/app/.venv/bin/pip install --upgrade pip", "/app/.venv/bin/pip install -r requirements.txt"]

[start]
    cmd = "/app/.venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app"