[variables]
    NIXPACKS_PYTHON_VERSION = "3.10"

[phases.setup]
    nixPkgs = ["cmake", "libglvnd", "gcc", "stdenv.cc.cc.lib", "xorg.libX11", "python310"]

[phases.install]
    # Global environment mein module call se install karenge
    cmds = [
        "python3 -m pip install --upgrade pip",
        "python3 -m pip install -r requirements.txt"
    ]

[start]
    # Gunicorn ko module ki tarah run karenge taaki path ka issue hi na rahe
    cmd = "python3 -m gunicorn --bind 0.0.0.0:$PORT app:app"